### ISSUE TITLE
Create new commands for generating lit protocol projects from templates

### ISSUE THREAD

**Issue by joshLong145** [LIT-Protocol/getlit#10]
A set of commands which let you quickly bootstrap a front end project letting users pick to include various Lit Protocol packages.
- Lit Auth Client
- Contracts SDK
- PKP-Signers
- pkp-cosmos
- pkp-ethers

The `lit-node-client` package should be included by default in generated projects.

We should let users choose from various front end frameworks including:
- React
- NextJS

**Comment by yhl125** [comment]
Hi @joshLong145, Can you review my PR?
